### PR TITLE
update followup extension

### PR DESCRIPTION
**Pull request by hannahburkhardt**
- set value when message is received from patient
- clear value when manual message is sent to patient

In the future, we may want to allow users to mark the patient as "followed-up" manually, without sending a message, from the ISACC web client.

### CODE REVIEW

**Comment by hannahburkhardt** [comment]
I believe the `SearchParameter` resource needs to look something like this:
```
{
  "resourceType" : "SearchParameter",
  "url" : "http://isacc.app/search-param-time-of-last-unfollowedup-message",
  "name" : "SearchParamTimeOfLastUnrespondedMessage",
  "status" : "active",
  "description" : "Search by time of the last message that the patient sent which has not received appropriate followup. The extension/value of the extension does not exist if the patient has no such message.",
  "code" : "time-of-last-unfollowedup-message",
  "base" : ["Patient"],
  "type" : "date",
  "expression" : "Patient.extension('http://isacc.app/time-of-last-unfollowedup-message').value"
}
```
After depositing this resource in our server, the HAPI server seems to recognize the new parameter, but I'm not getting the expected results when searching  like so: `https://launch.smarthealthit.org/v/r4/fhir/Patient?time-of-last-unfollowedup-message:missing=false`
Thoughts @ivan-c @pbugni @achen2401 ?

**Comment by achen2401** [comment]
@hannahburkhardt I am hoping to try this out when I am in front of a computer but should the `expression` be  `"Patient.extension('http://isacc.app/search-param-time-of-last-unfollowedup-message').value" `, matching the `url` you specified?  Or should the url be http://isacc.app/time-of-last-unfollowedup-message?  I found this discussion on line that might be helpful: https://github.com/Microsoft/fhir-server/issues/219

**Comment by achen2401** [comment]
@hannahburkhardt 
I tried this against SMIT launcher:
```
{
  "resourceType": "SearchParameter",
  "url": "http://hl7.org/fhir/SearchParameter/patient-extensions-Patient-SearchParamTimeOfLastUnrespondedMessage",
  "name": "SearchParamTimeOfLastUnrespondedMessage",
  "status": "active",
  "experimental": true,
  "description": "Search by time of the last message that the patient sent which has not received appropriate followup. The extension/value of the extension does not exist if the patient has no such message.",
  "code": "SearchParamTimeOfLastUnrespondedMessage",
  "base": ["Patient"],
  "type": "date",
  "expression": "Patient.extension('http://isacc.app/time-of-last-unfollowedup-message').value"
}
```
(see posted SearchParameter [here](https://launch.smarthealthit.org/v/r4/fhir/SearchParameter/1467986))

And then I did the search using `https://launch.smarthealthit.org/v/r4/fhir/Patient?SearchParamTimeOfLastUnrespondedMessage:missing=false` and that `seems` to work.  [Here](https://launch.smarthealthit.org/v/r4/fhir/Patient?SearchParamTimeOfLastUnrespondedMessage:missing=false) is the search result.

Although I only tested out on one patient and I haven't figured out how to sort this based on that extension yet though.

**Comment by achen2401** [comment]
Noting that when I tried, sorting only seemed to only work correctly if `:missing=false` is included in the search parameter:
Some of things I tried:
[example sort in desc order with :missing=false param - results seem correctly sorted](https://launch.smarthealthit.org/v/r4/fhir/Patient?SearchParamTimeOfLastUnrespondedMessage:missing=false&_sort=-SearchParamTimeOfLastUnrespondedMessage)
[example sort in asc order with :missing=false param - results seem correctly sorted](https://launch.smarthealthit.org/v/r4/fhir/Patient?SearchParamTimeOfLastUnrespondedMessage:missing=false&_sort=SearchParamTimeOfLastUnrespondedMessage)
[example sort without :missing=false param - results aren't correctly sorted](https://launch.smarthealthit.org/v/r4/fhir/Patient?SearchParamTimeOfLastUnrespondedMessage&_sort=-SearchParamTimeOfLastUnrespondedMessage)

**Comment by hannahburkhardt** [comment]
Amazing! Thanks @achen2401. It seems maybe the code (` "code" : "time-of-last-unresponded-message"`) and extension name (as shown in `"expression" : "Patient.extension('http://isacc.app/time-of-last-unfollowedup-message').value"`) cannot match?
I changed the search parameter's code like so (to avoid breaking naming and casing conventions for search parameters), and now it seems to work:
```
{
  "resourceType" : "SearchParameter",
  "url" : "http://isacc.app/search-param-time-of-last-unfollowedup-message",
  "name" : "SearchParamTimeOfLastUnrespondedMessage",
  "status" : "active",
  "description" : "Search by time of the last message that the patient sent which has not received appropriate followup. The extension/value of the extension does not exist if the patient has no such message.",
  "code" : "time-of-last-unresponded-message",
  "base" : ["Patient"],
  "type" : "date",
  "expression" : "Patient.extension('http://isacc.app/time-of-last-unfollowedup-message').value"
}
```
And the query:
`https://launch.smarthealthit.org/v/r4/fhir/Patient?time-of-last-unresponded-message:missing=false&_sort=time-of-last-unresponded-message`

**Comment by mcjustin** [comment]
https://www.pivotaltracker.com/story/show/184551635

**Review by pbugni — APPROVED** [review]
Nice work - looks great.

**Pull request merged**
