### PR TITLE
correct attribute access on care_team participant

### PR DESCRIPTION
**Pull request by pbugni**
resolve_reference() returns a fhirclient Object, not a JSON dict.

this should have been caught with #35 - my best guess is no patient under test had a valid careTeam.

### CODE REVIEW

**Comment by mcjustin** [comment]
> resolve_reference() returns a fhirclient Object, not a JSON dict.
> 
> this should have been caught with #35 - my best guess is no patient under test had a valid careTeam.

@pbugni , my tests earlier this evening (absent this PR's change) had odd results!
Test recipient: https://fhir.isacc.dev.cirg.uw.edu/fhir/Patient/1

Here's what I sent from my phone:
mcjustin_phone_screenshot_isacc_dev_20230912

Here's what isacc shows:
image

... namely:
1. The first message came through 4 times, the first time 15 minutes after I sent it.
2. Second msg came through w/in a minute.
3. Third msg never arrived.
4. Fourth msg came through w/in a minute.

Does that indicate some separate problem to you?

The recipient has two Practitioners in its CareTeam: https://fhir.isacc.dev.cirg.uw.edu/fhir/CareTeam/1349 

On a separate note, I think the dev systems isn't configured properly to enable the URL that's sent in the notification email:
`https://femr.isacc.dev.cirg.uw.edu/target?sof_client_id=MESSAGING&patient=1` 
 "Invalid or mis-configured SOF client specified. Unable to retrieve launch URL."

**Comment by pbugni** [comment]
@mcjustin recall yesterday, when i requested the parameters from the twilio error log page?  to fix the issue above, i personally re-posted those several times, as that was a certain replication of the problem.

in other words, i faked that response you see 4 times, via curl with the parameters you gave me.

**Comment by pbugni** [comment]
@mcjustin w/o any other changes (perhaps the reload yesterday?), i find the following to work as expected.  this is the link from the email:
> https://femr.isacc.dev.cirg.uw.edu/target?sof_client_id=MESSAGING&patient=1

**Comment by mcjustin** [comment]
> @mcjustin w/o any other changes (perhaps the reload yesterday?), i find the following to work as expected. this is the link from the email:
> 
> > https://femr.isacc.dev.cirg.uw.edu/target?sof_client_id=MESSAGING&patient=1

@pbugni  did you see @achen2401 's fix at https://github.com/uwcirg/cosri-patientsearch/pull/198 ?

**Comment by pbugni** [comment]
> @pbugni did you see @achen2401 's fix at [uwcirg/cosri-patientsearch#198](https://github.com/uwcirg/cosri-patientsearch/pull/198) ?

i did not, but that clearly explains why it went from broken to functional.

i do believe the issue behind this PR is fixed, and the other issues you report above are symptoms of my testing and what we're in the process of addressing via https://gitlab.cirg.washington.edu/infrastructure/puppet-admins/puppet-6-server/-/merge_requests/117.  anything outstanding here, @mcjustin ?

**Review by mcjustin — APPROVED** [review]

**Comment by mcjustin** [comment]
> > @pbugni did you see @achen2401 's fix at [uwcirg/cosri-patientsearch#198](https://github.com/uwcirg/cosri-patientsearch/pull/198) ?
> 
> i did not, but that clearly explains why it went from broken to functional.
> 
> i do believe the issue behind this PR is fixed, and the other issues you report above are symptoms of my testing and what we're in the process of addressing via https://gitlab.cirg.washington.edu/infrastructure/puppet-admins/puppet-6-server/-/merge_requests/117. anything outstanding here, @mcjustin ?

Sounds like a wrap!

**Pull request merged**
